name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install autoconf automake libtool

      - name: Generate configure script
        run: autoconf

      - name: Configure the project
        run: ./configure

      - name: Build the project
        run: make

      - name: Run tests
        run: make test
