name: C/C++ Linter

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: C/C++ Linter
        uses: cpp-linter/cpp-linter-action@v2.14.0
        with:
          style: ''  # Set to '' to disable clang-format, or specify a style like 'llvm'
          extensions: 'c,h,cpp,hpp,cc,hh,cxx,hxx'  # File extensions to lint
          tidy-checks: 'boost-*,bugprone-*,performance-*,readability-*,portability-*,modernize-*,clang-analyzer-*,cppcoreguidelines-*'  # Checks to run with clang-tidy
          repo-root: '.'  # Root directory of the repository
          version: '14'  # Version of clang-tools to use
          verbosity: 'info'  # Verbosity of the linter logs
          lines-changed-only: false  # Analyze all lines in a file
          files-changed-only: true  # Analyze only changed files
          ignore: '.github'  # Paths to ignore
          ignore-tidy: '.github'  # Paths for clang-tidy to ignore
          ignore-format: '.github'  # Paths for clang-format to ignore
          thread-comments: false  # Disable thread comments for feedback
          no-lgtm: true  # Disable LGTM comments
          step-summary: true  # Append content to the job summary
          file-annotations: true  # Enable file annotations for feedback
          extra-args: '-std=c++17 -Wall'  # Extra arguments for clang-tidy
          tidy-review: false  # Disable PR reviews from clang-tidy
          format-review: false  # Disable PR reviews from clang-format
          passive-reviews: true  # Prevent PR reviews from approving or requesting changes
          jobs: 0  # Number of jobs to run in parallel (0 uses all available CPU cores)
